info:
  component: Config Server


spring:
  jmx:
    default-domain: cloud.config.server

  cloud:
    config:
      server:
        git:
          uri:
            clone-on-start: true
            searchPaths:
server:
  address: 0.0.0.0
  port: ${application.port}

noteshub:
  configserver:
    security:
      basicAuth:
        username: ${spring.cloud.config.username}
        password: ${spring.cloud.config.password}
